mount:
  # Basic binaries and libraries
  - type: bind
    source: /root/.nix-profile/bin
    target: /bin
    readonly: true
  - type: bind
    source: /root/.nix-profile/bin
    target: /usr/bin
    readonly: true
  - type: bind
    source: /root/.nix-profile/lib
    target: /lib
    readonly: true
  - type: bind
    source: /root/.nix-profile/share
    target: /share
    readonly: true
  - type: bind
    source: /root/.nix-profile/etc
    target: /etc
    readonly: true
  - type: bind
    source: /nix
    target: /nix
    readonly: true
  - type: bind
    source: /dev/null
    target: /dev/null
  - type: bind
    source: /dev/urandom
    target: /dev/urandom
  - type: tmpfs
    target: /w
    data: size=512m,nr_inodes=8k
  - type: tmpfs
    target: /tmp
    data: size=512m,nr_inodes=8k
proc: true
workDir: /w
hostName: executor_server
domainName: executor_server
uid: 1536
gid: 1536
